name: format
on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 20.4.0

      - name: Install dependencies
        run: npm ci

      - name: Run npm format
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
