name: Prettier Format

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prettier Check
        uses: creyD/prettier_action@v4.3
        with:
          dry: false
          prettier_options: --write .
